CREATE DATABASE MERCADO_ZE

GO

USE MERCADO_ZE
CREATE TABLE CLIENTE
(
    CPF BIGINT NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    PONTOS_FIDELIDADE DECIMAL(11,2) NOT NULL,
    RUA VARCHAR(200) NOT NULL,
    NUMERO INT NOT NULL,
    BAIRRO VARCHAR(100) NOT NULL,
    CEP VARCHAR(20) NOT NULL,
    COMPLEMENTO VARCHAR(50) NOT NULL,
    NOME VARCHAR(200) NOT NULL
)


GO

USE MERCADO_ZE
CREATE TABLE PEDIDO

(    
    NUMERO INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    DATA_HORA DATE NOT NULL,
    PRODUTO_ID INT NOT NULL,
    CLIENTE_ID BIGINT NOT NULL,
    VALORTOTAL DECIMAL(18,0) NOT NULL

)


GO

USE MERCADO_ZE
CREATE TABLE PRODUTO

(    
    ID_PRODUTO INT NOT NULL,
    NOME VARCHAR(150) NOT NULL,
    DESCRICAO VARCHAR(250) NOT NULL,
    DATA_VENCIMENTO DATE NOT NULL,
    PRECO_UNITARIO DECIMAL(11,2) NOT NULL,
    UNIDADE VARCHAR(50) NOT NULL,
    QUANTIDADE_ESTOQUE INT NOT NULL

)    