SELECT TOP (1000) [CPF]
      ,[DATA_NASCIMENTO]
      ,[PONTOS_FIDELIDADE]
      ,[RUA]
      ,[NUMERO]
      ,[BAIRRO]
      ,[CEP]
      ,[COMPLEMENTO]
      ,[NOME]
  FROM [MERCADO_ZE].[dbo].[CLIENTE]